name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build package
        run: yarn build
